# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zhuima\Desktop\quantum\ui\Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(826, 618)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -10, 831, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label_2.setObjectName("label_2")
        self.frame1 = QtWidgets.QFrame(Form)
        self.frame1.setGeometry(QtCore.QRect(30, 280, 381, 131))
        self.frame1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1.setObjectName("frame1")
        self.label_3 = QtWidgets.QLabel(self.frame1)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 111, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame1)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.frame2 = QtWidgets.QFrame(Form)
        self.frame2.setGeometry(QtCore.QRect(430, 280, 381, 131))
        self.frame2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame2.setObjectName("frame2")
        self.label_7 = QtWidgets.QLabel(self.frame2)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 111, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame2)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 271, 31))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.frame3 = QtWidgets.QFrame(Form)
        self.frame3.setGeometry(QtCore.QRect(30, 440, 381, 131))
        self.frame3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame3.setObjectName("frame3")
        self.label_5 = QtWidgets.QLabel(self.frame3)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 111, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame3)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.frame4 = QtWidgets.QFrame(Form)
        self.frame4.setGeometry(QtCore.QRect(430, 440, 381, 131))
        self.frame4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame4.setObjectName("frame4")
        self.label_11 = QtWidgets.QLabel(self.frame4)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame4)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><img src=\":/spear/resource/logo.png\"/></p></body></html>"))
        self.label_2.setText(_translate("Form", "量子应用"))
        self.label_3.setText(_translate("Form", "投资组合优化"))
        self.label_4.setText(_translate("Form", "基于QAOA算法从备选金融产品中找到特定风险偏好类型下的最佳收益组合"))
        self.label_7.setText(_translate("Form", "量子期权定价"))
        self.label_8.setText(_translate("Form", "基于量子蒙特卡罗的期权定价算法"))
        self.label_5.setText(_translate("Form", "CRAMC"))
        self.label_6.setText(_translate("Form", "xxxxxx"))
        self.label_11.setText(_translate("Form", "用户异常行为检测"))
        self.label_12.setText(_translate("Form", "基于QGAN的异常行为检测"))
import resource_rc
